# -*- coding: utf-8 -*-
"""Amazon_streamlit_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fIPZ6qgw3EYQM4_VVOBDp7tt82-f1jEI
"""

import os

folders = [
    "amazon_app",
    "amazon_app/data",
    "amazon_app/assets"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

files = [
    "amazon_app/app.py",
    "amazon_app/requirements.txt",
    "amazon_app/data/customer_impact.csv",
    "amazon_app/data/amazon_labelled.csv",
    "amazon_app/data/predictions_test.csv",
    "amazon_app/data/shap_summary.csv",
    "amazon_app/data/classification_report.csv",
    "amazon_app/assets/shap_bar_DEAL_SEEKER.png",
    "amazon_app/assets/shap_bar_NICHE_EXPLORER.png",
    "amazon_app/assets/shap_bar_QUALITY_FIRST.png",
    "amazon_app/assets/shap_bar_SOCIAL_PROOF.png"
]

for file in files:
    open(file, 'a').close()

print("Folder structure created successfully!")

# Commented out IPython magic to ensure Python compatibility.
# %cd amazon_app

!pip install -r requirements.txt

!pip install pyngrok

from pyngrok import ngrok

ngrok.set_auth_token("3Ef81aWp4x8ShoneB4PYnZxdSrq_29EA7s5KtQx8P99C8BTpM")

!streamlit run app.py > streamlit.log 2>&1 &

from pyngrok import ngrok

public_url = ngrok.connect(8501)
print(public_url.public_url)