# -*- coding: utf-8 -*-
"""Amazon_ML_project_file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pcey2blJwb8HXdBqBdmyJnKCy44YI-PV
"""

# ==========================
# INSTALL DEPENDENCIES
# ==========================

!pip -q install imbalanced-learn xgboost lightgbm optuna vaderSentiment

import warnings
warnings.filterwarnings('ignore')

import os
import time
import pickle
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

OUTPUT_DIR = "/content/drive/MyDrive/AmazonSegmentationOutputs"
os.makedirs("outputs", exist_ok=True)
print("Output folder created:", OUTPUT_DIR)

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("features_final.csv")
df.head()

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (classification_report, confusion_matrix,
                             f1_score, ConfusionMatrixDisplay)
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns

# Segment 4 = UNMATCHED  → keep as class 4 but map names
# Task says target = segment_code with 4 classes (0-3) — we keep 4 (UNMATCHED) too
# since dropping it would lose 454 rows; we relabel mapping below
SEG_NAMES = {0:'DEAL_SEEKER', 1:'NICHE_EXPLORER', 2:'QUALITY_FIRST',
             3:'SOCIAL_PROOF', 4:'UNMATCHED'}
'''
DROP_COLS = [
    'product_id',                            # identifier
    'price_disc','price_actual',             # raw prices (engineered versions kept)
    'discount_pct','rating_count',           # raw (log/ratio versions kept)
]'''

DROP_COLS = [
    'product_id',                            # identifier
    'price_disc','price_actual',             # raw prices (engineered versions kept)
    'discount_pct','rating_count',           # raw (log/ratio versions kept)
    'score_DEAL_SEEKER',                     # LEAKAGE: Direct components of target
    'score_QUALITY_FIRST',                   # LEAKAGE
    'score_SOCIAL_PROOF',                    # LEAKAGE
    'score_NICHE_EXPLORER'                   # LEAKAGE
]
# any leftover string/object columns
obj_cols = df.select_dtypes('object').columns.tolist()
DROP_COLS += obj_cols

DROP_COLS = [c for c in DROP_COLS if c in df.columns]
feature_cols = [c for c in df.columns if c not in DROP_COLS + ['segment_code']]

X = df[feature_cols].copy()
y = df['segment_code'].copy()
ids = df['product_id'].copy() if 'product_id' in df.columns else pd.Series(range(len(df)))

print(f"Features: {X.shape[1]}  |  Classes: {y.value_counts().sort_index().to_dict()}")

# ════════════════════════════════════════════════════════════════
# 1. TRAIN / TEST SPLIT  (80/20 stratified)
# ════════════════════════════════════════════════════════════════
X_train, X_test, y_train, y_test, id_train, id_test = train_test_split(
    X, y, ids, test_size=0.2, random_state=42, stratify=y)

print(f"Train: {X_train.shape}  Test: {X_test.shape}")
print(f"Train class dist: {pd.Series(y_train).value_counts().sort_index().to_dict()}")

# ════════════════════════════════════════════════════════════════
# 2. SMOTE on X_train only
# ════════════════════════════════════════════════════════════════
# SMOTE needs k_neighbors < min_class_samples; NICHE_EXPLORER has only ~6 in train
min_class = pd.Series(y_train).value_counts().min()
k = min(5, min_class - 1)
print(f"SMOTE k_neighbors={k}  (min class in train = {min_class})")
sm = SMOTE(k_neighbors=k, random_state=42)
X_res, y_res = sm.fit_resample(X_train, y_train)
print(f"After SMOTE: {X_res.shape}  |  {pd.Series(y_res).value_counts().sort_index().to_dict()}")

# ════════════════════════════════════════════════════════════════
# 3. BASELINE — Logistic Regression
# ════════════════════════════════════════════════════════════════
print("\n── Logistic Regression baseline ──")
scaler = StandardScaler()
X_res_sc  = scaler.fit_transform(X_res)
X_test_sc = scaler.transform(X_test)

lr = LogisticRegression(max_iter=1000, random_state=42, multi_class='multinomial')
lr.fit(X_res_sc, y_res)
lr_pred  = lr.predict(X_test_sc)
lr_f1    = f1_score(y_test, lr_pred, average='macro')
print(f"LR  Macro-F1: {lr_f1:.4f}")

# ════════════════════════════════════════════════════════════════
# 4. XGBoost base
# ════════════════════════════════════════════════════════════════
n_classes = y.nunique()
print(f"\n── XGBoost base (num_class={n_classes}) ──")
xgb_base = XGBClassifier(
    objective='multi:softprob', num_class=n_classes,
    eval_metric='mlogloss', use_label_encoder=False,
    n_estimators=300, random_state=42, verbosity=0, n_jobs=-1)
xgb_base.fit(X_res, y_res)
xgb_base_pred = xgb_base.predict(X_test)
xgb_base_f1   = f1_score(y_test, xgb_base_pred, average='macro')
print(f"XGB base Macro-F1: {xgb_base_f1:.4f}")

# ════════════════════════════════════════════════════════════════
# 5. OPTUNA — tune XGBoost (50 trials, 5-fold stratified CV)
# ════════════════════════════════════════════════════════════════
print("\n── Optuna tuning XGBoost (50 trials × 5-fold) ──")
trial_f1s = []

def objective(trial):
    params = dict(
        objective      = 'multi:softprob',
        num_class      = n_classes,
        eval_metric    = 'mlogloss',
        use_label_encoder = False,
        verbosity      = 0,
        n_jobs         = -1,
        random_state   = 42,
        n_estimators   = trial.suggest_int('n_estimators',   100, 800),
        max_depth      = trial.suggest_int('max_depth',        3,   8),
        learning_rate  = trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        subsample      = trial.suggest_float('subsample',     0.6, 1.0),
        colsample_bytree = trial.suggest_float('colsample_bytree', 0.6, 1.0),
    )
    clf  = XGBClassifier(**params)
    cv   = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    scores = cross_val_score(clf, X_res, y_res, cv=cv,
                             scoring='f1_macro', n_jobs=-1)
    val = scores.mean()
    trial_f1s.append(val)
    return val

study = optuna.create_study(direction='maximize',
                            sampler=optuna.samplers.TPESampler(seed=42))
t0 = time.time()
study.optimize(objective, n_trials=50, show_progress_bar=False)
print(f"Optuna done in {time.time()-t0:.1f}s  |  Best CV F1: {study.best_value:.4f}")
print(f"Best params: {study.best_params}")

# Convergence curve
best_so_far = np.maximum.accumulate(trial_f1s)
fig, ax = plt.subplots(figsize=(10, 4))
ax.plot(range(1, len(trial_f1s)+1), trial_f1s,    color='#aac4e0', alpha=0.7, lw=1, label='Trial F1')
ax.plot(range(1, len(best_so_far)+1), best_so_far, color='#1e6fa8', lw=2.2,  label='Best so far')
ax.axhline(study.best_value, color='crimson', ls='--', lw=1.4, label=f'Best = {study.best_value:.4f}')
ax.set_xlabel('Trial', fontsize=11); ax.set_ylabel('Macro-F1 (5-fold CV)', fontsize=11)
ax.set_title('Optuna Convergence — XGBoost Hyperparameter Search', fontsize=13, fontweight='bold')
ax.legend(fontsize=10); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('outputs/optuna_convergence.png', dpi=150, bbox_inches='tight')
plt.close()
print("Saved: optuna_convergence.png")

# Retrain best XGB on full SMOTE train set
best_params = {**study.best_params,
               'objective':'multi:softprob','num_class':n_classes,
               'eval_metric':'mlogloss','use_label_encoder':False,
               'verbosity':0,'n_jobs':-1,'random_state':42}
xgb_best = XGBClassifier(**best_params)
xgb_best.fit(X_res, y_res)
xgb_pred  = xgb_best.predict(X_test)
xgb_proba = xgb_best.predict_proba(X_test)
xgb_f1    = f1_score(y_test, xgb_pred, average='macro')
print(f"XGB tuned Macro-F1 (test): {xgb_f1:.4f}")

# ════════════════════════════════════════════════════════════════
# 6. LightGBM multiclass
# ════════════════════════════════════════════════════════════════
print("\n── LightGBM ──")
lgb = LGBMClassifier(
    objective='multiclass', num_class=n_classes,
    n_estimators=500, learning_rate=0.05,
    max_depth=6, subsample=0.8, colsample_bytree=0.8,
    random_state=42, verbosity=-1, n_jobs=-1)
lgb.fit(X_res, y_res)
lgb_pred  = lgb.predict(X_test)
lgb_proba = lgb.predict_proba(X_test)
lgb_f1    = f1_score(y_test, lgb_pred, average='macro')
print(f"LGB Macro-F1: {lgb_f1:.4f}")

# ════════════════════════════════════════════════════════════════
# 7. ENSEMBLE (0.6 XGB + 0.4 LGB)
# ════════════════════════════════════════════════════════════════
final_proba = 0.6 * xgb_proba + 0.4 * lgb_proba
ens_pred    = np.argmax(final_proba, axis=1)
ens_f1      = f1_score(y_test, ens_pred, average='macro')
print(f"\nEnsemble Macro-F1: {ens_f1:.4f}")

# ════════════════════════════════════════════════════════════════
# 8. OUTPUTS
# ════════════════════════════════════════════════════════════════
seg_labels = [SEG_NAMES[i] for i in sorted(SEG_NAMES)]

# ─ Confusion matrix heatmap ─
present_classes = sorted(y_test.unique())
present_names   = [SEG_NAMES[i] for i in present_classes]

cm = confusion_matrix(y_test, ens_pred, labels=present_classes)
fig, ax = plt.subplots(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=present_names, yticklabels=present_names,
            linewidths=0.5, linecolor='white', ax=ax,
            cbar_kws={'shrink':0.8})
ax.set_xlabel('Predicted Segment', fontsize=12)
ax.set_ylabel('True Segment', fontsize=12)
ax.set_title('Confusion Matrix — Ensemble (XGB 0.6 + LGB 0.4)', fontsize=13, fontweight='bold')
plt.xticks(rotation=30, ha='right', fontsize=9)
plt.yticks(rotation=0, fontsize=9)
plt.tight_layout()
plt.savefig('outputs/confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.close()
print("Saved: confusion_matrix.png")

# ─ Classification report ─
cr = classification_report(y_test, ens_pred,
                            labels=present_classes,
                            target_names=present_names,
                            output_dict=True)
cr_df = pd.DataFrame(cr).T
print("\n── Classification Report (Ensemble) ──")
print(classification_report(y_test, ens_pred,
                             labels=present_classes,
                             target_names=present_names))
cr_df.to_csv('outputs/classification_report.csv')
print("Saved: classification_report.csv")

# ─ Macro-F1 comparison table ─
print("\n══ Model Comparison ══════════════════")
print(f'  Logistic Regression : {lr_f1:.4f}')
print(f'  XGBoost (base)      : {xgb_base_f1:.4f}')
print(f'  XGBoost (tuned)     : {xgb_f1:.4f}')
print(f'  LightGBM            : {lgb_f1:.4f}')
print(f'  Ensemble (XGB+LGB)  : {ens_f1:.4f}')
print('═══════════════════════════════════')

# Bar chart comparison
model_names = ['Logistic\nRegression','XGBoost\n(base)','XGBoost\n(tuned)','LightGBM','Ensemble']
model_f1s   = [lr_f1, xgb_base_f1, xgb_f1, lgb_f1, ens_f1]
bar_colors  = ['#aaaaaa','#6dbf8a','#3b9ebf','#f4845f','#9b59b6']

fig, ax = plt.subplots(figsize=(10, 5))
bars = ax.bar(model_names, model_f1s, color=bar_colors, edgecolor='white', linewidth=0.8, width=0.55)
for bar, v in zip(bars, model_f1s):
    ax.text(bar.get_x()+bar.get_width()/2, v+0.005, f'{v:.4f}',
            ha='center', va='bottom', fontsize=11, fontweight='bold')
ax.set_ylim(0, min(1.0, max(model_f1s)+0.12))
ax.set_ylabel('Macro-F1', fontsize=12)
ax.set_title('Model Macro-F1 Comparison', fontsize=13, fontweight='bold')
ax.axhline(max(model_f1s), color='crimson', ls='--', lw=1.2, alpha=0.6, label='Best')
ax.legend(fontsize=9); ax.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig('outputs/model_comparison.png', dpi=150, bbox_inches='tight')
plt.close()
print("Saved: model_comparison.png")

# ─ Feature importance (XGB tuned) ─
fi = pd.Series(xgb_best.feature_importances_, index=feature_cols).sort_values(ascending=False).head(20)
fig, ax = plt.subplots(figsize=(10, 7))
fi[::-1].plot(kind='barh', color='#3b9ebf', edgecolor='white', ax=ax)
ax.set_title('Top 20 Feature Importances — XGBoost (tuned)', fontsize=13, fontweight='bold')
ax.set_xlabel('Importance Score', fontsize=11)
plt.tight_layout()
plt.savefig('outputs/feature_importance.png', dpi=150, bbox_inches='tight')
plt.close()
print("Saved: feature_importance.png")

# ═══════════════════════════════════════════════════════════════
# 9. SAVE MODELS
# ═══════════════════════════════════════════════════════════════



with open('outputs/best_model.pkl', 'wb') as f:
    pickle.dump(xgb_best, f)

with open('outputs/lgb_model.pkl', 'wb') as f:
    pickle.dump(lgb, f)

print("Saved: best_model.pkl, lgb_model.pkl")

# ═══════════════════════════════════════════════════════════════
# 10. EXPORT PREDICTIONS
# ═══════════════════════════════════════════════════════════════

preds_df = pd.DataFrame({
    'product_id': id_test.values,
    'true_segment': y_test.map(SEG_NAMES).values,
    'pred_segment': pd.Series(ens_pred).map(SEG_NAMES).values,
    'proba_deal': final_proba[:, 0],
    'proba_niche': final_proba[:, 1],
    'proba_quality': final_proba[:, 2],
    'proba_social': final_proba[:, 3],
    'proba_unmatched': final_proba[:, 4] if final_proba.shape[1] > 4 else 0.0,
})

preds_df.to_csv(
    'outputs/predictions_test.csv',
    index=False
)

print(f"Saved: predictions_test.csv ({len(preds_df)} rows)")
print("\n✅ Pipeline complete.")

from google.colab import files

files.download('outputs/predictions_test.csv')
files.download('outputs/classification_report.csv')

